name = "blog-admin"
main = "src/index.js"
compatibility_date = "2023-12-01"

[vars]
GITHUB_OWNER = "lishanganshijie-hue"
GITHUB_REPO = "firefly-astro0509"
GITHUB_BRANCH = "main"
POSTS_PATH = "src/content/posts"
IMAGE_PATH = "images"
BLOG_URL = "https://blogo.ccwu.cc"
PHOTO_OWNER = "lishanganshijie-hue"
PHOTO_REPO = "photo"
PHOTO_BRANCH = "main"
PHOTO_PATH = "images"
PROXY_BASE = "https://views.ccwu.cc/img"
